const samples=[
["Preamble of the Constitution","UPSC Polity","20 May 2024","preamble",["UPSC","Polity"]],["Fundamental Rights – Overview","UPSC Polity","19 May 2024","rights",["UPSC","Polity"]],["Physical Divisions of India","Geography","18 May 2024","map",["Geography"]],["Governor – Powers & Functions","UPSC Polity","18 May 2024","governor",["UPSC","Polity"]],["Revolt of 1857 – Causes","SSC History","17 May 2024","revolt",["SSC","History"]],["Mauryan Empire – Key Points","SSC History","16 May 2024","mauryan",["SSC","History"]],["Sectors of Indian Economy","Economy","15 May 2024","economy",[]],["Water Resources – Overview","Geography","14 May 2024","water",["Geography"]]
].map(([title,subject,date,type,categories],i)=>({id:"sample"+i,title,subject,date,type,categories}));
const $=s=>document.querySelector(s);let notes=[],category="All Notes",isAdmin=false;
const escapeHtml=v=>{const e=document.createElement("div");e.textContent=v;return e.innerHTML};
function preview(n){if(n.imageUrl)return `<img class="note-image" src="${n.imageUrl}" alt="${escapeHtml(n.title)} uploaded note">`;const c={preamble:"<h3>Preamble of the Constitution</h3><p>WE, THE PEOPLE OF INDIA, having solemnly resolved…</p><p>Justice · Liberty · Equality · Fraternity</p><div class='diagram'>⚖</div>",rights:"<h3>Fundamental Rights</h3><p>• Right to Equality</p><p>• Right to Freedom</p><p>• Right against Exploitation</p><p>• Cultural & Educational Rights</p>",map:"<h3>INDIA — PHYSICAL DIVISIONS</h3><div class='diagram'>⌁ ◒ ⌁</div><p>Himalayas · Northern Plains · Plateau</p>",governor:"<h3>The Governor</h3><div class='diagram'>▣</div><p>Appointment · Tenure · Functions</p>",revolt:"<h3>The Revolt of 1857</h3><p><b>Causes</b></p><p>Political · Economic · Social · Military</p><div class='diagram'>♞</div>",mauryan:"<h3>Mauryan Empire</h3><p>Founder: Chandragupta Maurya</p><p>Capital: Pataliputra</p><p>Ashoka · Dhamma · Edicts</p><div class='diagram'>♜</div>",economy:"<h3>Indian Economy — Sectors</h3><div class='diagram'>◔ ◑ ◕</div><p>Primary · Secondary · Tertiary</p>",water:"<h3>Water Resources of India</h3><p>Sources</p><div class='diagram'>┬ ┴</div><p>Rivers · Lakes · Wells</p>"}[n.type];return `<div class="preview">${c}</div>`}
function render(){const term=$("#note-search").value.trim().toLowerCase();let list=notes.filter(n=>(category==="All Notes"||n.categories?.includes(category)||n.subject.includes(category))&&(`${n.title} ${n.subject}`).toLowerCase().includes(term));if($("#sort-notes").value==="title")list.sort((a,b)=>a.title.localeCompare(b.title));$("#notes-grid").innerHTML=list.map(n=>{let k=n.subject.includes("History")?"history":n.subject.includes("Geography")?"geography":n.subject.includes("Economy")?"economy":"";let date=n.date||new Date(n.createdAt).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});return `<article class="note-card">${preview(n)}<div class="note-content"><span class="subject-chip ${k}">${escapeHtml(n.subject)}</span><p class="note-title">${escapeHtml(n.title)}</p><div class="note-meta"><span>${date} · 1 Image</span>${isAdmin&&n.imageUrl?`<button class="delete-note" data-id="${n.id}">Remove</button>`:"⋮"}</div></div></article>`}).join("");$("#empty-notes").hidden=list.length>0;$("#page-title").textContent=category;$("#note-total").textContent=`${list.length} notes available`;$("#all-count").textContent=notes.length;$("#showing-count").textContent=`Showing 1 to ${list.length} of ${notes.length} notes`}
async function api(url,options){const r=await fetch(url,options),v=await r.json().catch(()=>({}));if(!r.ok)throw Error(v.error||"Something went wrong.");return v}
function login(){ $("#admin-login-message").textContent="";$("#admin-password").value="";$("#admin-dialog").showModal() }function upload(){if(!isAdmin)return login();$("#upload-dialog").showModal()}function setAdmin(v){isAdmin=v;render()}
$("#category-nav").addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(!b)return;category=b.dataset.category;document.querySelectorAll(".category").forEach(x=>x.classList.toggle("active",x===b));render()});$("#note-search").addEventListener("input",render);$("#sort-notes").addEventListener("change",render);$("#admin-login-button").onclick=login;$("#admin-area-button").onclick=login;$("#open-upload").onclick=upload;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());
$("#admin-login-form").addEventListener("submit",async e=>{e.preventDefault();const msg=$("#admin-login-message");msg.classList.remove("error");msg.textContent="Checking password…";try{await api("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:$("#admin-password").value})});setAdmin(true);$("#admin-dialog").close();upload()}catch(x){msg.textContent=x.message;msg.classList.add("error")}});
$("#upload-form").addEventListener("submit",e=>{e.preventDefault();const file=$("#note-file").files[0],msg=$("#upload-message");msg.classList.remove("error");if(!file||(!file.type.match(/^image\/jpeg$/)&&!/\.jpe?g$/i.test(file.name))){msg.textContent="Please choose a JPG or JPEG image.";msg.classList.add("error");return}if(file.size>5*1024*1024){msg.textContent="Choose an image smaller than 5 MB.";msg.classList.add("error");return}msg.textContent="Publishing note…";const reader=new FileReader();reader.onload=async()=>{try{const v=await api("/api/admin/notes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:$("#note-title").value.trim(),subject:$("#note-subject").value,imageData:reader.result})});notes.unshift({...v.note,categories:[]});render();$("#upload-form").reset();msg.textContent="The note is now visible to students."}catch(x){msg.textContent=x.message;msg.classList.add("error")}};reader.readAsDataURL(file)});
$("#notes-grid").addEventListener("click",async e=>{const b=e.target.closest("[data-id]");if(!b)return;try{await api("/api/admin/notes/"+b.dataset.id,{method:"DELETE"});notes=notes.filter(n=>n.id!==b.dataset.id);render()}catch(x){alert(x.message)}});
(async()=>{try{const [n,a]=await Promise.all([api("/api/notes"),api("/api/admin/me")]);notes=[...n.notes.map(x=>({...x,categories:[]})),...samples];setAdmin(a.admin)}catch{notes=samples;render()}})();
